### ISSUE TITLE
BiMap is not a constructor

### ISSUE THREAD

**Issue by jespinozaa** [educastellano/bidirectional-map#3]
Hello, I use this package in a couple of developments and when testing the new version 1.1.0 strangely it tells me the following message "BiMap is not a constructor" even though the implementation is quite simple, I even get the same message copying the example from the documentation , please it would be helpful if you will check

![image](https://user-images.githubusercontent.com/27874645/138211033-3be190bc-12e6-428d-a516-cfc3160dbcaf.png)

**Comment by educastellano** [comment]
Hey @jespinozaa, I used a newer version of babel, you might need to require the module like this:

```
const BiMap = require('bidirectional-map').default
```

Although it works fine without `.default` on my side... Which version of node are you using?

**Comment by jespinozaa** [comment]
I tried it with node v12.22.3 and v14.17.5 with the same result. But with the "default" hack
it works again 
thanks for your time!

**Comment by educastellano** [comment]
It wasn't working for me either, I was actually trying the previous version 😅

I've released a new version keeping the previous way to import the package. Thanks for reporting the issue!
